export enum PageType {
	Cover = 'cover',
	BlackJack = 'blackJack',
	CashOrCrash = 'cashOrCrash',
	Craps = 'craps',
	DreamCatcher = 'dreamCatcher',
	CrazyTime = 'crazyTime',
	Gonzo = 'gonzo',
	Holdem = 'holdem',
	LighteningDice = 'lighteningDice',
	Megaball = 'megaBall',
	Monopoly = 'monopoly',
	Roulette = 'roulette',
	SicBo = 'sicBo',
}
